---
apiVersion: v1
kind: Service
metadata:
  name: solid-pancake-jaeger
spec:
  type: ClusterIP
  selector:
    app: solid-pancake-jaeger
  ports:
    - name: agent2collector
      port: 14250
    - name: web-ui
      port: 16686
---
apiVersion: v1
kind: Service
metadata:
  name: solid-pancake-nats
spec:
  type: ClusterIP
  selector:
    app: solid-pancake-nats
  ports:
    - name: nats
      port: 4222
